spring:
  application:
    name: connection-service

  neo4j:
    uri: bolt://localhost:7687
    username: neo4j
    password: root1234

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 9012
  servlet:
    context-path: /connections

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
